#!/usr/bin/env bash

n=$1

case "$n" in

    astik) echo "Hi astik";;
    
    sampa) echo "Hello mom";;

    buddy) echo "Here comes trouble";;

    guy) echo "Hehe comeon gay";;

    *) echo "idk who you are :)" ;;
esac
